[project]
name = "Studio-Reservation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
  { name = "Lyric" }
]
requires-python = ">=3.14"
dependencies = [
    "supabase>=2.31.0", 
    "flask>=3.1.3", 
    "dotenv>=0.9.9"
]
tool.vercel.entrypoint = "src/Main.py"

[project.scripts]
main_script = "Main:main"

[build-system]
requires = ["uv_build >= 0.12.1, <0.13.0"]
build-backend = "uv_build"